---
- hosts: srsunonprodervers
  gather_facts: False
  remote_user: axf24lz
  tasks:
  - name: Set authorized key took from file
    authorized_key:
      user: axf24lz
      state: present
      key: "{{ lookup('file', '/home/axf24lz/.ssh/id_rsa.pub') }}"
