---
- hosts: prccnonprodservers
  gather_facts: false
  remote_user: afernandez
  become: yes
  become_user: root

  vars:
    slack_webhook_url: "https://hooks.slack.com/services/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"

  tasks:
  - name: Check last system update
    command: dnf history
    register: dnf_history_output

  - name: Debug dnf history output
    debug:
      var: dnf_history_output.stdout_lines

  - name: Parse dnf history output for updates
    set_fact:
      update_entries: >
        {{
          dnf_history_output.stdout_lines
          | select("search", " U ")
          | map("regex_replace", "^\\s*(\\d+).*$", "\\1")
          | list
        }}

  - name: Debug parsed update entries
    debug:
      var: update_entries

  - name: Get latest update entry
    set_fact:
      latest_update_id: "{{ update_entries | max }}"

  - name: Debug latest update id
    debug:
      var: latest_update_id

  - name: Get details of the latest update entry
    command: dnf history info "{{ latest_update_id }}"
    register: latest_update_info

  - name: Debug latest update info
    debug:
      var: latest_update_info.stdout

  - name: Format update information as table
    set_fact:
      update_info_table: |
        *Latest update information on host {{ inventory_hostname }}:*
        ```
        {{ latest_update_info.stdout }}
        ```

  - name: Prepare Slack message body for updates found
    set_fact:
      slack_message: >
        {{
          {
            "text": update_info_table
          } | to_json
        }}

  - name: Send message to Slack
    uri:
      url: "{{ slack_webhook_url }}"
      method: POST
      headers:
        Content-Type: "application/json"
      body: "{{ slack_message }}"
      status_code: 200
