---
- name: Install Nagios on Ubuntu 24.04
  hosts: awssanbox
  become: yes

  tasks:
    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install prerequisites
      apt:
        name:
          - autoconf
          - gcc
          - libc6
          - make
          - wget
          - unzip
          - apache2
          - apache2-utils
          - php
          - libgd-dev
          - libmcrypt-dev
          - libssl-dev
          - bc
          - gawk
          - dc
          - build-essential
          - snmp
          - libnet-snmp-perl
          - gettext
        state: present

    - name: Create Nagios user
      user:
        name: nagios
        shell: /bin/bash
        create_home: yes

    - name: Create nagcmd group
      group:
        name: nagcmd
        state: present

    - name: Add nagios user to nagcmd group
      user:
        name: nagios
        groups: nagcmd
        append: yes

    - name: Add www-data user to nagcmd group
      user:
        name: www-data
        groups: nagcmd
        append: yes

    - name: Download Nagios source code
      get_url:
        url: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.5.4.tar.gz
        dest: /tmp/nagios-4.5.4.tar.gz

    - name: Extract Nagios source code
      unarchive:
        src: /tmp/nagios-4.5.4.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Configure Nagios
      command: ./configure --with-nagios-group=nagios --with-command-group=nagcmd
      args:
        chdir: /tmp/nagios-4.5.4

    - name: Compile Nagios
      command: make all
      args:
        chdir: /tmp/nagios-4.5.4

    - name: Install Nagios core binaries and web interface files
      command: make install
      args:
        chdir: /tmp/nagios-4.5.4

    - name: Install Nagios command mode
      command: make install-commandmode
      args:
        chdir: /tmp/nagios-4.5.4

    - name: Install Nagios init script
      command: make install-init
      args:
        chdir: /tmp/nagios-4.5.4

    - name: Install Nagios config files
      command: make install-config
      args:
        chdir: /tmp/nagios-4.5.4

    - name: Install Apache configuration for Nagios
      copy:
        src: /tmp/nagios-4.5.4/sample-config/httpd.conf
        dest: /etc/apache2/sites-available/nagios.conf
        mode: '0644'

    - name: Enable Nagios site in Apache
      file:
        src: /etc/apache2/sites-available/nagios.conf
        dest: /etc/apache2/sites-enabled/nagios.conf
        state: link

    - name: Enable CGI and Rewrite modules in Apache
      apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - cgi
        - rewrite

    - name: Install Nagios plugins
      apt:
        name: nagios-plugins
        state: present

    - name: Copy Nagios plugins to the correct directory
      copy:
        src: /usr/lib/nagios/plugins/
        dest: /usr/local/nagios/libexec/
        remote_src: yes

    - name: Verify Nagios configuration
      command: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg

    - name: Set Nagios admin password
      expect:
        command: htpasswd -c /usr/local/nagios/etc/htpasswd.users nagiosadmin
        responses:
          'Password:': "H@mp51r3-Adm1n\n"
          'Re-type password:': "H@mp51r3-Adm1n\n"
      register: htpasswd_result
      failed_when: "'password updated successfully' not in htpasswd_result.stdout"

    - name: Enable and restart Nagios and Apache services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      loop:
        - nagios
        - apache2

