---
- name: Test Slack notification
  hosts: prccnonprodservers
  vars_files:
    - vault.yml
  tasks:
    - name: Send test message to Slack
      community.general.slack:
        token: "{{ slack_webhook }}"
        msg: "This is a test message from Ansible."
        channel: "Alberto Fernandez"  # Replace with your Slack channel
        username: "AnsibleBot"
        icon_emoji: ":robot_face:"
        link_names: true
        parse: "full"
