---
- name: Test directory creation and file copying
  hosts: prccnonprodservers
  vars:
    dest_base_path: "/tmp/html-report"
    src_path: "/tmp/server_info"
    current_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
  tasks:
    - name: Create directory with the current date on the local host
      file:
        path: "{{ dest_base_path }}/{{ current_date }}"
        state: directory
        mode: '0755'

    - name: Fetch the passwd file from the remote host
      ansible.builtin.fetch:
        src: /etc/passwd
        dest: "{{ dest_base_path }}/{{ current_date }}/passwd"
        flat: yes
      delegate_to: "{{ remote_host }}"
      remote_user: "{{ remote_user }}"
      become: yes
      become_method: sudo
