---
- name: Check uptime of servers
  hosts: prccnonprodservers
  gather_facts: yes
  remote_user: afernandez
  become: yes

  tasks:
    - name: Retrieve uptime
      ansible.builtin.command: uptime
      register: uptime_output

    - name: Display uptime
      debug:
        msg: "Server {{ inventory_hostname }} uptime: {{ uptime_output.stdout }}"
